export const TOUCH_GALLERY_NEXT = 'TOUCH_GALLERY_NEXT'
export const TOUCH_GALLERY_PREV = 'TOUCH_GALLERY_PREV'
export const TOUCH_GALLERY_CLOSE = 'TOUCH_GALLERY_CLOSE'
export const TOUCH_GALLERY_OPEN = 'TOUCH_GALLERY_OPEN'